version: "3"
services:

  Narnia-ruins:
    container_name: narnia-ruins
    image: lloesche/valheim-server:latest
    cap_add:
      - sys_nice
    restart: always
    env_file:
      - narnia-ruins.env
    ports:      
      - "2457:2457/udp"
    volumes:
      - /opt/valheim/narnia-ruins-server/config:/config 
      - /opt/valheim/narnia-ruins-server/data:/opt/valheim
     
  Narnia:
    container_name: narnia
    image: lloesche/valheim-server:latest
    cap_add:
      - sys_nice
    restart: always
    env_file:
      - narnia.env
    ports:
      - "2456:2456/udp"
    volumes:
      - /opt/valheim/narnia-server/config:/config 
      - /opt/valheim/narnia-server/data:/opt/valheim
     stop_grace_period: 2m
